language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
sudo: false
env:
  PERL_CPANM_OPT: "--notest --force --skip-satisfied"
  TEST_VALGRIND: true
before_install:
  - "cpanm Dist::Zilla"
  # libtest-valgrind-perl provides valgrind dependencies, but this is needed
  # to add something visible on @INC
  - "cpanm Test::Valgrind"
  - "dzil authordeps | cpanm"
  - "dzil listdeps --author | cpanm"
  - "dzil build"
install:
  - "dzil listdeps | cpanm"
script:
  - "dzil test --release"
after_success:
  # For collection of code coverage metrics
  - "cpanm Devel::Cover::Report::Codecov"
  - "cpanm Dist::Zilla::App::Command::cover"
  - "dzil cover -report codecov"
addons:
  apt:
    packages:
    - libtest-valgrind-perl
